version: '3'

services:
  nginx:
    container_name: 'noka_nginx'
    build: ./docker/nginx
    platform: linux/x86_64
    ports:
      - 8080:80
      - 80:80
    volumes:
      - ./:/var/www/src
      - ./docker/nginx/log/nginx/error.log:/var/log/nginx/error.log
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/htpasswd:/etc/nginx/htpasswd
    # depends_on:
      # - php-fpm
    # tty: true
    working_dir: /var/www/src
    # env_file: .env
    networks:
      - backend
        # aliases:
        #   - nginx
    # links:
    #   - php-fpm

  php-fpm:
    container_name: 'noka_php'
    build: ./docker/php-fpm
    platform: linux/x86_64
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/src
      - ./docker/nginx/log:/var/log
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    # tty: true
    working_dir: /var/www/src
    # env_file: .env
    networks:
      - backend
        # aliases:
        #   - php-fpm
  
  mysql:
    container_name: 'noka_mysql'
    build: ./docker/mysql
    platform: linux/x86_64
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/log:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      DB_NAMES: benkiapp_dev
      MYSQL_DATABASE: benkiapp_dev
      # command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
      # command: --innodb-use-native-aio=0 # <- 追加！
    # restart: always
    tty: true
    networks:
      - backend
      # backend:
      #   aliases:
      #     - mysql

networks:
  backend:
    driver: bridge

